services:
  dashboard:
    environment:
      DISPLAY: ${DISPLAY}
      QT_QPA_PLATFORM: xcb
      QT_X11_NO_MITSHM: "1"

    volumes:
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix